config/routes.rb
Blog::Application.routes.draw do

  resources :articles do
    resources :comments
  end

  devise_for :users

  root :to => "articles#index"

end

app/models/article.rb
class Article
  include Mongoid::Document

  field :title
  field :author
  field :published_at, :type => DateTime
  field :body
  
  #key :title
  
  embeds_many :comments
  referenced_in :user

  
  validates :title, :author, :body, :presence => true

  def long_title
    "#{title} - #{published_at}" 
  end
  
  def published?
    published_at.present?
  end  

  def owned_by?(owner)
    return false unless owner.is_a? User
    user == owner
  end


end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :name
  field :email  
  field :body
  field :published_at, :type => Date
  
  embedded_in :article, :inverse_of => :comments
  
  validates :name, :email, :body, :presence => true
  validate :article_should_be_published
  validates :email,  :length => { :within => 5..50 },
                    :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }
  
  
  def article_should_be_published
    errors.add(:article_id, "is not published yet") if article && !article.published?
  end
    
end

app/models/user.rb
class User
  include Mongoid::Document

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :name, :email, :password, :password_confirmation

  validates_uniqueness_of :email, :case_sensitivy => false
  validate :email, :presence => true,
                    :uniqueness => true,
                    :length => { :within => 5..50 },
                    :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }
  
  validate :password,  :presence => true,
                        :confirmation => true
  
  references_many :articles
  references_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
      #format.mobile 
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = current_user.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = current_user.articles.build(params[:article])

    if @article.save
      redirect_to(@article, :notice => 'Article was successfully created, pal.')
    else
      render "new"
    end
    
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = current_user.articles.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_article
    
  def create
    @comment = @article.comments.create(params[:comment])
        
    if @comment.save
      redirect_to @article, :notice => 'Thanks for your comment'
    else
      @comment.destroy
      render "articles/show"
    end
  end
  
  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to @article, :notice => 'Comment deleted'
  end
  
  private
  
    def load_article
      @article = Article.find(params[:article_id])
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Creates a submit button with the given name with a cancel link 
  # Accepts two arguments: Form object and the cancel link name 
  def submit_or_cancel(form, name='Cancel')
    form.submit + " or " + link_to(name, 'javascript:history.go(-1);', :class => 'cancel')
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.erb
<%= div_for article do %>
	<header>
	  <h1><%= link_to article.title, article %></h1>
		<% if article.owned_by?(current_user) %>		
			<ul>
				<li><%= link_to "Edit", edit_article_path(article) %></li>
				<li><%= link_to "Delete", article, :confirm => "Are you sure?", :method => :delete %></li>
			</ul>
		<% end %>
	</header>
	<div><%= article.body %></div>
	<footer>
		<p>Comments: <%= link_to article.comments.count, article_path(article, :anchor => "comments") %></p>
	</footer>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset>
		<ol>
			<li>
				<%= f.label :title %>
				<%= f.text_field :title %>
			</li>
			<li>
				<%= f.label :author %>
				<%= f.text_field :author %>
			</li>
			<li>
				<%= f.label :body %>
				<%= f.text_area :body %>
			</li>
			<li>
				<%= f.label :published_at %>
				<%= f.datetime_select :published_at %>
			</li>
		</ol>
	</fieldset>
	
  <fieldset class="actions">
    <%= submit_or_cancel(f) %>
  </fieldset>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render @articles %>

app/views/articles/new.html.erb
<h1>New article</h1>

<p><%= current_user.articles.to_a %></p>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render @article %>

<section id="comments">
	<% if @article.comments.empty? %>
		<h1>You have no comments so far.</h1>
	<% else %>
		<h1>Comments</h1>
		<%= render @article.comments %>
	<% end %>
	<footer>
		<h1>Add A New Comment</h1>
		<%= render :file => 'comments/new' %>
	</footer>
</section>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <h1>
    <%= comment.name %> &lt;<%= comment.email %>&gt; said:    
    <% if @article.owned_by? current_user %>
      <span class='actions'>
        <%= link_to 'Delete', [@article, comment], :confirm => 'Are you sure?', :method => :delete %>
      </span>
    <% end %>
  </h1>
  <%= comment.body %>
<% end %>

app/views/comments/new.html.erb
<% if @comment.errors.any? %>
  <div class="error_explanation">
    <h1><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h1>
    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([@article, @comment]) do |f| %>
	<fieldset>
		<ol>
			<li>
				<%= f.label :name %>
				<%= f.text_field :name %>
			</li>
			<li>
				<%= f.label :email %>
				<%= f.text_field :email %>
			</li>
			<li>
				<%= f.label :body %>
				<%= f.text_area :body, :rows => 10 %>
			</li>
		</ol>
	</fieldset>

  <fieldset class="actions">
		<%= f.submit 'Add' %>
	</fieldset>

<% end %>

app/views/comments/testme.html.erb
<%= render @article %>
	<p>Comments are: <%= @article.comments %></p>

app/views/layouts/application.html.erb
<!doctype html>

<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	
	<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame 
	Remove this if you use the .htaccess -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Blog</title>
	<meta name="description" content="My Blog">
	<meta name="author" content="Dimitar Haralanov">

	<!--  Mobile viewport optimized: j.mp/bplateviewport -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
	<link rel="shortcut icon" href="/favicon.ico">
	<link rel="apple-touch-icon" href="/apple-touch-icon.png">

	<%= stylesheet_link_tag 'style' %>
	<%= stylesheet_link_tag 'formalize' %>

  <%= javascript_include_tag 'modernizr', 'jquery.min.js', 'rails', 'application' %>
	<%= javascript_include_tag 'formalize' %>
  <%= csrf_meta_tag %>
</head>
<body>

	<header>
		<div class="content-wrapper">
			<hgroup>
				<a href="/"><h1>MyBlog</h1></a>
				<h2>This Is My First Experimental Blog Platform Written In Rails!</h2>
			</hgroup>
			<nav role="actions">
				<%- if user_signed_in? -%>
					<p>Hello, <strong><%= current_user.name %></strong></p>
					<ul>
						<li><%= link_to 'New Article', new_article_path %></li>
						<li><%= link_to 'Logout', destroy_user_session_path %></li>
					</ul>
				<%- else -%>
					<p><%= link_to 'Login', new_user_session_path %></p>
				<%- end -%>
			</nav>
		</div><!-- end of .content-wrapper -->
	</header>

	<section id="main">
		<div class="content-wrapper">
			<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
			<%= content_tag :p, alert, :class => 'alert' if alert.present? %>

			
			<%= yield %>
		</div>
	</section>
	
	<footer>
		<div class="content-wrapper">
			<p>&copy; 2010 Dimitar Haralanov</p>
		</div>
	</footer>

</body>
</html>